[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Non-Fiction Writing: Techniques and Strategies for More Effective and Engaging Writing with Technology"
